version: "3.7"

services:
    app:
        image: ${APP_NAME}-app-dev:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app_dev
        environment:
            APP_ENV: dev
            OPCACHE_VALIDATE_TIMESTAMPS: 1
        depends_on:
            - db
        volumes:
            - ./app:/var/www/html:rw,cached
    web:
        image: ${APP_NAME}-web:local
        build:
            args:
                ASSETS_IMAGE: "${APP_NAME}-app-dev:local"
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - ${APP_PORT}:80
        depends_on:
            - app
        volumes:
            - ./app/public:/var/www/html/public:ro,delegated
    cache:
        image: ${APP_NAME}-cache:local
        build:
            context: .
            dockerfile: ./docker/varnish/Dockerfile
        ports:
            - ${APP_CACHE_PORT}:80
        depends_on:
            - web
        links:
            - web
    db:
        image: mysql:8.0
        environment:
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - db_storage:/var/lib/mysql
    node:
        image: node:14
        volumes:
          - ./app:/app:rw,cached
        ports:
            - "8080:8080"
        working_dir: /app
        command: ["yarn", "dev-server", "--host=0.0.0.0"]
volumes:
    db_storage: {}
