#index:
#    path: /
#    controller: App\Controller\DefaultController::index

newStore:
    path: /shop
    controller: App\Controller\StoreController::newStore

getStore:
    path: /shop/{id}
    controller: App\Controller\StoreController::getStore
