#index:
#    path: /
#    controller: App\Controller\DefaultController::index

shop:
    path: /shop
    controller: App\Controller\Shop::getShop

listItems:
    path: /listItems
    controller: App\Controller\Shop::listItems